- name: Check mandatory variables are defined
  assert:
    that:
      - redis.bind_address is defined

- name: Prepare configuration values
  ansible.builtin.set_fact:
    redis: "{{ defaults.redis | combine(redis) }}"
